sudo: required 
services: 
  - docker

before_install:
  - docker build -t agruberg/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true agruberg/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "frontend"
  env: "Frontend-env"
  bucket_name: "elasticbeanstalk-us-east-1-143011406134"
  bucket_path: "frontend"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_id: "$AWS_SECRET_KEY"

